// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcRTDulT3ktRsaQ1xMvNwWbizTgt1ikc4',
    appId: '1:1977428712:web:4a2c353e24e6a980d4375d',
    messagingSenderId: '1977428712',
    projectId: 'pretzel-eab3d',
    authDomain: 'pretzel-eab3d.firebaseapp.com',
    storageBucket: 'pretzel-eab3d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtJBrxyVonxjglbnZW7h4z0srcrXxJXjI',
    appId: '1:1977428712:android:ea3bf17d5356f5b4d4375d',
    messagingSenderId: '1977428712',
    projectId: 'pretzel-eab3d',
    storageBucket: 'pretzel-eab3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYFy1QgjRX_m-8bwCGOvwact6nsxb-G3g',
    appId: '1:1977428712:ios:a4e9eabce3f94974d4375d',
    messagingSenderId: '1977428712',
    projectId: 'pretzel-eab3d',
    storageBucket: 'pretzel-eab3d.firebasestorage.app',
    iosBundleId: 'com.example.pretzelApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYFy1QgjRX_m-8bwCGOvwact6nsxb-G3g',
    appId: '1:1977428712:ios:a4e9eabce3f94974d4375d',
    messagingSenderId: '1977428712',
    projectId: 'pretzel-eab3d',
    storageBucket: 'pretzel-eab3d.firebasestorage.app',
    iosBundleId: 'com.example.pretzelApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcRTDulT3ktRsaQ1xMvNwWbizTgt1ikc4',
    appId: '1:1977428712:web:dcda09fb76e608bbd4375d',
    messagingSenderId: '1977428712',
    projectId: 'pretzel-eab3d',
    authDomain: 'pretzel-eab3d.firebaseapp.com',
    storageBucket: 'pretzel-eab3d.firebasestorage.app',
  );
}
